#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-TagFilter
version:      0.08
version_from: TagFilter.pm
installdirs:  site
requires:
    HTML::Parser:                  1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
